version: "3.9"
   
services:
  web:
    image: full_stack_py
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
